import type { BaseStyle } from '.'

// code from https://github.com/sindresorhus/cli-boxes/blob/main/boxes.jsons
export const borderMap = {
  single: {
    topLeft: '┌',
    top: '─',
    topRight: '┐',
    right: '│',
    bottomRight: '┘',
    bottom: '─',
    bottomLeft: '└',
    left: '│',
    leftMiddle: '├',
    rightMiddle: '┤',
    topMiddle: '┬',
    bottomMiddle: '┴',
    middleMiddle: '┼',
  },
  double: {
    topLeft: '╔',
    top: '═',
    topRight: '╗',
    right: '║',
    bottomRight: '╝',
    bottom: '═',
    bottomLeft: '╚',
    left: '║',
    leftMiddle: '╠',
    rightMiddle: '╣',
    topMiddle: '╦',
    bottomMiddle: '╩',
    middleMiddle: '╬',
  },
  round: {
    topLeft: '╭',
    top: '─',
    topRight: '╮',
    right: '│',
    bottomRight: '╯',
    bottom: '─',
    bottomLeft: '╰',
    left: '│',
    leftMiddle: '├',
    rightMiddle: '┤',
    topMiddle: '┬',
    bottomMiddle: '┴',
    middleMiddle: '┼',
  },
  bold: {
    topLeft: '┏',
    top: '━',
    topRight: '┓',
    right: '┃',
    bottomRight: '┛',
    bottom: '━',
    bottomLeft: '┗',
    left: '┃',
    leftMiddle: '┣',
    rightMiddle: '┫',
    topMiddle: '┳',
    bottomMiddle: '┻',
    middleMiddle: '╋',
  },
  singleDouble: {
    topLeft: '╓',
    top: '─',
    topRight: '╖',
    right: '║',
    bottomRight: '╜',
    bottom: '─',
    bottomLeft: '╙',
    left: '║',
    leftMiddle: '╟',
    rightMiddle: '╢',
    topMiddle: '╥',
    bottomMiddle: '╨',
    middleMiddle: '╫',
  },
  doubleSingle: {
    topLeft: '╒',
    top: '═',
    topRight: '╕',
    right: '│',
    bottomRight: '╛',
    bottom: '═',
    bottomLeft: '╘',
    left: '│',
    leftMiddle: '╞',
    rightMiddle: '╡',
    topMiddle: '╤',
    bottomMiddle: '╧',
    middleMiddle: '╪',
  },
  classic: {
    topLeft: '+',
    top: '-',
    topRight: '+',
    right: '|',
    bottomRight: '+',
    bottom: '-',
    bottomLeft: '+',
    left: '|',
    leftMiddle: '+',
    rightMiddle: '+',
    topMiddle: '+',
    bottomMiddle: '+',
    middleMiddle: '+',
  },
  arrow: {
    topLeft: '↘',
    top: '↓',
    topRight: '↙',
    right: '←',
    bottomRight: '↖',
    bottom: '↑',
    bottomLeft: '↗',
    left: '→',
    leftMiddle: '→',
    rightMiddle: '←',
    topMiddle: '↑',
    bottomMiddle: '↓',
    middleMiddle: '+',
  },
}

export const NEWLINE = '\n'
export const SPACE = ' '

export const DefaultStyle: BaseStyle = {
  border: false,
  borderStyle: 'single',
  borderColor: '#fff',
}
